services:
  memcached:
    image: ${MEMCACHED_IMAGE:-memcached:1.6-alpine@sha256:c29847751abb41f4c268c84fb3087fee05d4edcbda44409ccb5086e26148e8a7}
    restart: unless-stopped
    networks:
      default:
networks:
  default:
